<?php
namespace app\common\model;

use think\Model;

class Tests extends Model{
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getIds(){
        $ids=$this->db()->select();
        $newIds=[];
        foreach ($ids as $k => $v){
            if($v['type']=='1'){
                $newIds[1][]=$v['id'];
            }elseif($v['type']=='2'){
                $newIds[2][]=$v['id'];
            }elseif($v['type']=='3'){
                $newIds[3][]=$v['id'];
            }
        }
        return $newIds;
    }

}


?>